name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: cd Driscod; dotnet restore
    - name: Build
      run: cd Driscod; dotnet build --configuration Release --no-restore
    - name: Test
      run: cd Driscod; dotnet test --no-restore --verbosity normal
